### ISSUE TITLE
add code to job/ app to handle NewBoiler

### ISSUE THREAD

**Issue by NLaws** [NREL/REopt_API#305]

**Comment by rathod-b** [comment]
Hi Nick, I have added Boiler and ExistingBoiler as inputs and outputs to the model and I think the changes should work. When I send a request with Boiler and ExistingBoiler specified they show up as inputs in the GET response post optimization. However, I see there is no SpaceHeatingLoad inputs specified in models.py, so I cant really test it from Postman. Should i go ahead and add SpaceHeatingLoadInputs as well?

```julia
┌ Warning: Not creating Boiler because there is no heating load.
└ @ REopt C:\Users\BRATHOD\.julia\dev\REopt\src\core\scenario.jl:271
```
