### ISSUE TITLE
add API job/ tests with posts that include all optional model keys

### ISSUE THREAD

**Issue by hdunham** [NREL/REopt_API#347]
All models that don't get created unless the user includes them (e.g. CHP) need to be included in a test post. We need to do this to make sure all the Django fields are aligned with the REopt.jl struct fields.

**Comment by rathod-b** [comment]
I will include a test which includes all model keys with `error-msgs` branch. A possible bug / pending item is how we handle prod factor for Wind. If a user provides the `Wind` key but not the prod factor, it defaults to `[]` which causes failure in REopt. This issue will need a bit more digging.

**Comment by rathod-b** [comment]
Added test `test_superset_input_fields` in https://github.com/NREL/REopt_API/blob/master/reoptjl/test/test_job_endpoint.py. This test is meant to exercise all possible inputs/outputs in API V3 (as long as it is incrementally updated along with API v3 updates).
