### ISSUE TITLE
Sync /job/models defaults with API V2 instead of V1

### ISSUE THREAD

**Issue by Bill-Becker** [NREL/REopt_API#371]
At least some of the defaults for Django model fields such as `PV.installed_cost_per_kw` and `PV.om_cost_per_kw` are based on `v1` defaults, and they should be changed to `v2` defaults.

**Comment by rathod-b** [comment]
Found 10 fields where v1 defaults were different from v2/stable defaults. I will update these as part of `pass-messages` branch. 
![image](https://user-images.githubusercontent.com/83797218/192641063-ff913670-e0b0-4af9-850f-6b675d03546d.png)

**Comment by Bill-Becker** [comment]
Thanks!

**Comment by rathod-b** [comment]
Updated misaligned defaults in https://github.com/NREL/REopt_API/pull/370/commits/996ce723a5cf1e7e781e1fe68a73fbf2f3761150.
