### ISSUE TITLE
Return cooling_defaults for all API calls to simulated_load endpoint that include cooling

### ISSUE THREAD

**Issue by zolanaj** [NREL/REopt_API#491]
**Note: for support questions and enhancement suggestions please use the REopt Forum (under development)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When running the UI and including a cooling load and/or technology, changing the building type does not change the default annual cooling load whereas the default updates for hot thermal and electric loads. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- Open the UI under the development branch
- Add CHP, then Absorption Chiller
- Under Cooling Load section, Check the box labeled "Enter custom annual or monthly thermal energy amounts" 
- Change building type in the dropdown menu for building type multiple times

* **What is the expected behavior?**
Updating the building type via the dropdown menu should change the default annual load.

* **What is the motivation / use case for changing the behavior?**
Allows proper tracking of the default cooling load by building in the UI

* **Please tell us about your environment:**
  
  - REopt API Version: X.X.X
  - Operating System: [all | TypeScript X.X | ES6/7 | ES5 | Dart]
  - Python version: 3.x
  - Julia version: 1.x

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Bill-Becker** [comment]
@zolanaj In the current API, if I call /simulated_load with different load_type=electric and cooling_doe_ref_name=[any CRB], I get the cooling_defaults which should update the UI with default annual_tonhour. However, when I actually send annual_tonhour with load_type=cooling, that's when I don't get the cooling_defaults. Is that latter part what we're missing?

Either way, it would be good to setup a branch of the API calling the REopt.jl branch in https://github.com/NREL/REopt.jl/pull/252 so we can test that it does what we want in the API before merging in the REopt.jl PR.

**Comment by zolanaj** [comment]
@Bill-Becker your view of the situation matches mine.  The use case for refreshing the defaults with load_type=cooling is in the UI; when changing the building type in the drop-down menu for the cooling load profile (after absorption chiller or cold TES is checked), the default annual ton-hours are not updated (these aren't displayed in the current version of the Web Tool but are intended to be added in v3).  

I agree with the plan - I'll set up a branch of the API to test this and follow up!

**Comment by zolanaj** [comment]
After further discussion, we won't add `cooling_defaults` to the `simulated_load` call when `load_type == 'cooling'`; rather, we will update the UI calls so that the default is linked to the electric load and cooling building type, using the existing version of `simulated_load`.
